### ISSUE TITLE
ストーリー制作

### ISSUE THREAD

**Issue by Saekikenta** [Saekikenta/Cinderella#6]

**Comment by Saekikenta** [comment]
ストーリーから外れない程度のクイズの制作

**Comment by KouOka** [comment]
岡崎担当
進捗度0%

**Comment by KouOka** [comment]
[シンデレラ.docx](https://github.com/Saekikenta/Cinderella/files/1034637/default.docx)
岡崎

**Comment by KouOka** [comment]
クイズ・ストーリー
進捗度100%

**Comment by KouOka** [comment]
[シンデレラ.docx](https://github.com/Saekikenta/Cinderella/files/1034639/default.docx)
クイズ・ストーリー
進捗度100%
